[package]
name = "lean-playground"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
lean-parser = { path = "../../syntax/lean-parser" }
lean-syn-expr = { path = "../../syntax/lean-syn-expr" }
